cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'gcc'
brew 'git'
brew 'heroku'
brew 'keychain'
brew 'node'
brew 'python'
brew 'tmux'
brew 'todo-txt'

cask 'dropbox'
cask 'google-chrome'
cask 'iterm2'
cask 'keybase'
cask 'visual-studio-code'
